import type { Build } from "@/components/gear-card"

export const mockBuilds: Build[] = [
  {
    id: "b1",
    name: "Thunderstrike Operative",
    author: "OPERATIVE_7X",
    category: "PvP",
    weapon: "Assault Rifle",
    element: "Shock",
    tier: "S",
    rating: 5,
    views: 14230,
    description:
      "High-burst PvP build focused on chain-shocking enemies with stacking electro damage. Maximizes crit rate and elemental DMG for devastating burst windows.",
    stats: { critRate: 68, critDmg: 245, elementalDmg: 180, defense: 2100, hp: 28000, stamina: 145 },
    gear: {
      helmet: "Stormcaller Visor",
      jacket: "Charged Plate MK-IV",
      pants: "Insulated Combat Legs",
      gloves: "Arc Conductor Grips",
      boots: "Thunderstep Runners",
      accessory: "Lightning Core Pendant",
    },
  },
  {
    id: "b2",
    name: "Inferno Tank",
    author: "BlazeKnight",
    category: "PvE",
    weapon: "Shotgun",
    element: "Burn",
    tier: "S",
    rating: 5,
    views: 11502,
    description:
      "Tanky frontline PvE build using burn synergies to melt through elite mobs. High HP pool with defensive layering and fire-based AoE.",
    stats: { critRate: 32, critDmg: 160, elementalDmg: 155, defense: 4200, hp: 45000, stamina: 120 },
    gear: {
      helmet: "Inferno Crown",
      jacket: "Magma Plate Armor",
      pants: "Firewalker Greaves",
      gloves: "Ember Guard Gauntlets",
      boots: "Ashstep Warboots",
      accessory: "Flame Heart Amulet",
    },
  },
  {
    id: "b3",
    name: "Frostbite Sniper",
    author: "IcePhantom",
    category: "PvP",
    weapon: "Sniper",
    element: "Frost",
    tier: "S",
    rating: 4,
    views: 9870,
    description:
      "Long-range precision build with frost debuffs that slow enemies before the killing blow. Extreme crit damage scaling for one-shot potential.",
    stats: { critRate: 85, critDmg: 290, elementalDmg: 120, defense: 1600, hp: 22000, stamina: 160 },
    gear: {
      helmet: "Cryo Targeting HUD",
      jacket: "Glacial Ghillie Suit",
      pants: "Frozen Stalker Legs",
      gloves: "Permafrost Marksman Grips",
      boots: "Silent Ice Treads",
      accessory: "Absolute Zero Scope",
    },
  },
  {
    id: "b4",
    name: "Hybrid Vanguard",
    author: "OPERATIVE_7X",
    category: "Hybrid",
    weapon: "Assault Rifle",
    element: "None",
    tier: "A",
    rating: 4,
    views: 7250,
    description:
      "Balanced all-rounder build that performs well in both PvP and PvE. Focuses on raw kinetic damage with solid defensive stats.",
    stats: { critRate: 55, critDmg: 200, elementalDmg: 0, defense: 3200, hp: 35000, stamina: 140 },
    gear: {
      helmet: "Tactical Ops Helmet",
      jacket: "Reinforced Combat Vest",
      pants: "Adaptive Field Pants",
      gloves: "Multi-Role Gauntlets",
      boots: "All-Terrain Strikers",
      accessory: "Versatility Module",
    },
  },
  {
    id: "b5",
    name: "Plasma Rush",
    author: "VoltRunner",
    category: "PvP",
    weapon: "SMG",
    element: "Shock",
    tier: "A",
    rating: 4,
    views: 6430,
    description:
      "Aggressive close-range SMG build with electric arc damage that chains between clustered opponents. High mobility and stamina focused.",
    stats: { critRate: 48, critDmg: 190, elementalDmg: 165, defense: 1800, hp: 25000, stamina: 185 },
    gear: {
      helmet: "Voltage Visor",
      jacket: "Charged Runner Vest",
      pants: "Ion Flow Leggings",
      gloves: "Spark Grip Pros",
      boots: "Surge Sprint Boots",
      accessory: "Tesla Reaction Ring",
    },
  },
  {
    id: "b6",
    name: "Pyroclasm Heavy",
    author: "MagmaLord",
    category: "PvE",
    weapon: "Heavy",
    element: "Burn",
    tier: "A",
    rating: 3,
    views: 4870,
    description:
      "Explosive-focused PvE build centered on area denial with napalm zones. Excellent for clearing hordes and zone control in co-op.",
    stats: { critRate: 25, critDmg: 140, elementalDmg: 195, defense: 3800, hp: 40000, stamina: 100 },
    gear: {
      helmet: "Blast Shield Dome",
      jacket: "Ordnance Carrier Rig",
      pants: "Fireproof Ballistic Legs",
      gloves: "Detonator Mitts",
      boots: "Impact Resistant Boots",
      accessory: "Inferno Core Module",
    },
  },
  {
    id: "b7",
    name: "Glacier Blade",
    author: "OPERATIVE_7X",
    category: "PvP",
    weapon: "Melee",
    element: "Frost",
    tier: "S",
    rating: 5,
    views: 12100,
    description:
      "Melee-only frost build with insane close-quarters burst. Creates frost patches on heavy attacks that slow and shatter frozen enemies.",
    stats: { critRate: 72, critDmg: 275, elementalDmg: 145, defense: 2800, hp: 30000, stamina: 175 },
    gear: {
      helmet: "Berserker Frost Helm",
      jacket: "Crystalline Battle Coat",
      pants: "Ice Runner Leggings",
      gloves: "Permafrost Knuckles",
      boots: "Glacier Dash Boots",
      accessory: "Cryo Heart Pendant",
    },
  },
  {
    id: "b8",
    name: "Sentinel Defender",
    author: "WallOfSteel",
    category: "PvE",
    weapon: "Shotgun",
    element: "None",
    tier: "B",
    rating: 3,
    views: 3200,
    description:
      "Pure defense tank build with maximum HP and armor. Ideal for holding chokepoints and protecting squads in high-tier PvE content.",
    stats: { critRate: 15, critDmg: 110, elementalDmg: 0, defense: 4800, hp: 48000, stamina: 95 },
    gear: {
      helmet: "Fortress Helm",
      jacket: "Titanium Bulwark",
      pants: "Reinforced Plating",
      gloves: "Shield Bearer Grips",
      boots: "Immovable Anchors",
      accessory: "Guardian Core",
    },
  },
  {
    id: "b9",
    name: "Spark Duelist",
    author: "DualWield99",
    category: "PvP",
    weapon: "Pistol",
    element: "Shock",
    tier: "B",
    rating: 3,
    views: 2950,
    description:
      "Agile pistol build for skilled players who rely on precision and mobility. Shock rounds stun targets briefly on crit hits.",
    stats: { critRate: 62, critDmg: 220, elementalDmg: 100, defense: 1400, hp: 20000, stamina: 190 },
    gear: {
      helmet: "Duelist Targeting Eye",
      jacket: "Light Weave Jacket",
      pants: "Agility Runners",
      gloves: "Quick Draw Gloves",
      boots: "Phantom Step Shoes",
      accessory: "Reflex Booster Ring",
    },
  },
]
